[package]
name = "ev3"
version = "0.5.1"
authors = ["Massimiliano Mantione <massimiliano.mantione@gmail.com>"]
edition = "2018"
description = "High level EV3 API"
license = "MIT"

[dependencies]
ev3rt = "0.5.0"
